// In-memory data and helpers for perfumes, preferencias y reviews.
// Las imageUrl son ejemplos (Unsplash) y pueden reemplazarse por fotos reales de frascos.
import { Perfume, PreferenceAction, UserPreferences, UserReview } from '../models/domain';

const perfumes: Perfume[] = [
  {
    id: 'p1',
    name: 'Aqua Marine Spirit',
    brand: 'Lumen',
    year: 2023,
    concentration: 'EDT',
    family: 'acuatico',
    notes: {
      top: ['bergamota', 'limon', 'menta'],
      heart: ['notas marinas', 'jazmin', 'lavanda'],
      base: ['cedro', 'almizcle', 'ambar gris'],
    },
    tags: ['acuatico', 'marino', 'ozonico', 'dia', 'verano', 'casual'],
    summary: 'Fresco salino que recuerda un dia luminoso cerca del mar.',
    averageRating: 4.5,
    ratingCount: 384,
    averageLongevityHours: 6,
    averageIntensity: 'media',
    usageStats: { day: 80, night: 20, summer: 85, winter: 15, office: 60, date: 35 },
    imageUrl: 'https://images.unsplash.com/photo-1506617420156-8e4536971650?auto=format&fit=crop&w=900&q=80',
    backgroundTheme: 'aquatic-blue',
    primaryColorHex: '#0ea5e9',
    secondaryColorHex: '#38bdf8',
    buyLinks: [
      { label: 'Ver en tienda A', url: 'https://example.com/aqua-marine' },
      { label: 'Ver en tienda B', url: 'https://example.com/aqua-marine-2' },
    ],
  },
  {
    id: 'p2',
    name: 'Noir Essence',
    brand: 'Maison Nord',
    year: 2022,
    concentration: 'EDP',
    family: 'oriental ambarado',
    notes: {
      top: ['pimienta rosa', 'ciruela'],
      heart: ['jazmin sambac', 'incienso'],
      base: ['patchouli', 'ambar', 'vainilla'],
    },
    tags: ['nocturno', 'ambarado', 'especiado', 'invierno', 'noche', 'sensual'],
    summary: 'Ambar oscuro con incienso y vainilla cremosa para noches frias.',
    averageRating: 4.7,
    ratingCount: 512,
    averageLongevityHours: 10,
    averageIntensity: 'fuerte',
    usageStats: { day: 25, night: 75, summer: 25, winter: 75, office: 20, date: 70 },
    imageUrl: 'https://images.unsplash.com/photo-1506617420156-14b6a9d64c8b?auto=format&fit=crop&w=900&q=80',
    backgroundTheme: 'dark-leather',
    primaryColorHex: '#111827',
    secondaryColorHex: '#4b5563',
    buyLinks: [
      { label: 'Ver en tienda A', url: 'https://example.com/noir-essence' },
      { label: 'Ver en tienda B', url: 'https://example.com/noir-essence-2' },
    ],
  },
  {
    id: 'p3',
    name: 'Citrus Bloom',
    brand: 'Atelier Verde',
    year: 2024,
    concentration: 'EDT',
    family: 'citrico floral',
    notes: {
      top: ['pomelo', 'bergamota', 'mandarina'],
      heart: ['petitgrain', 'neroli', 'hojas verdes'],
      base: ['almizcle blanco', 'cedro claro'],
    },
    tags: ['citrico', 'verde', 'dia', 'primavera', 'casual', 'oficina'],
    summary: 'Explosion de citricos chispeantes con un corazon verde limpio.',
    averageRating: 4.3,
    ratingCount: 290,
    averageLongevityHours: 5,
    averageIntensity: 'media',
    usageStats: { day: 90, night: 10, summer: 70, winter: 30, office: 75, date: 40 },
    imageUrl: 'https://images.unsplash.com/photo-1524592094714-0f0654e20314?auto=format&fit=crop&w=900&q=80',
    backgroundTheme: 'citrus-yellow',
    primaryColorHex: '#facc15',
    secondaryColorHex: '#f97316',
    buyLinks: [
      { label: 'Ver en tienda A', url: 'https://example.com/citrus-bloom' },
      { label: 'Ver en tienda B', url: 'https://example.com/citrus-bloom-2' },
    ],
  },
  {
    id: 'p4',
    name: 'Velvet Oud',
    brand: 'Al Zahra',
    year: 2021,
    concentration: 'Parfum',
    family: 'amaderado oud',
    notes: {
      top: ['azafran', 'frambuesa'],
      heart: ['rosa damascena', 'oud'],
      base: ['ambar', 'vainilla', 'maderas oscuras'],
    },
    tags: ['oud', 'amaderado', 'rosas', 'noche', 'invierno', 'formal'],
    summary: 'Oud sedoso con rosas y un fondo ambarado dulce.',
    averageRating: 4.8,
    ratingCount: 640,
    averageLongevityHours: 12,
    averageIntensity: 'bestia',
    usageStats: { day: 15, night: 85, summer: 20, winter: 80, office: 10, date: 85 },
    imageUrl: 'https://images.unsplash.com/photo-1524592094714-0f0654e20314?auto=format&fit=crop&w=900&q=80&sat=-30',
    backgroundTheme: 'dark-leather',
    primaryColorHex: '#1f2937',
    secondaryColorHex: '#92400e',
    buyLinks: [
      { label: 'Ver en tienda A', url: 'https://example.com/velvet-oud' },
      { label: 'Ver en tienda B', url: 'https://example.com/velvet-oud-2' },
    ],
  },
  {
    id: 'p5',
    name: 'Alpine Moss',
    brand: 'Nordic Air',
    year: 2020,
    concentration: 'EDT',
    family: 'verde aromatico',
    notes: {
      top: ['pino', 'limon', 'menta'],
      heart: ['lavanda', 'musgo de roble'],
      base: ['vetiver', 'cedro', 'almizcle blanco'],
    },
    tags: ['verde', 'bosque', 'alpino', 'dia', 'primavera', 'senderismo'],
    summary: 'Sensacion de bosque humedo y limpio con vetiver brillante.',
    averageRating: 4.2,
    ratingCount: 220,
    averageLongevityHours: 7,
    averageIntensity: 'media',
    usageStats: { day: 85, night: 15, summer: 60, winter: 40, office: 55, date: 30 },
    imageUrl: 'https://images.unsplash.com/photo-1498842812179-c81beecf902c?auto=format&fit=crop&w=900&q=80',
    backgroundTheme: 'woody-brown',
    primaryColorHex: '#166534',
    secondaryColorHex: '#065f46',
    buyLinks: [
      { label: 'Ver en tienda A', url: 'https://example.com/alpine-moss' },
      { label: 'Ver en tienda B', url: 'https://example.com/alpine-moss-2' },
    ],
  },
  {
    id: 'p6',
    name: 'Desert Amber',
    brand: 'Sahara Atelier',
    year: 2019,
    concentration: 'EDP',
    family: 'ambar especiado',
    notes: {
      top: ['cardamomo', 'clavos'],
      heart: ['canela', 'resinas'],
      base: ['ambar', 'benjui', 'sandalwood'],
    },
    tags: ['ambar', 'especiado', 'calido', 'noche', 'otoño', 'invierno'],
    summary: 'Ambar resinoso con especias doradas y base cremosa.',
    averageRating: 4.6,
    ratingCount: 340,
    averageLongevityHours: 9,
    averageIntensity: 'fuerte',
    usageStats: { day: 30, night: 70, summer: 25, winter: 75, office: 25, date: 65 },
    imageUrl: 'https://images.unsplash.com/photo-1489515217757-5fd1be406fef?auto=format&fit=crop&w=900&q=80',
    backgroundTheme: 'gourmand-warm',
    primaryColorHex: '#b45309',
    secondaryColorHex: '#f97316',
    buyLinks: [
      { label: 'Ver en tienda A', url: 'https://example.com/desert-amber' },
      { label: 'Ver en tienda B', url: 'https://example.com/desert-amber-2' },
    ],
  },
  {
    id: 'p7',
    name: 'Midnight Leather',
    brand: 'Axis',
    year: 2021,
    concentration: 'Parfum',
    family: 'cuero ahumado',
    notes: {
      top: ['pimienta negra', 'notas metalicas'],
      heart: ['cuero', 'tabaco', 'incienso'],
      base: ['oud', 'abedul ahumado', 'almizcle oscuro'],
    },
    tags: ['cuero', 'ahumado', 'tabaco', 'noche', 'invierno', 'rock'],
    summary: 'Cuero oscuro con toque de tabaco dulce y humo elegante.',
    averageRating: 4.4,
    ratingCount: 280,
    averageLongevityHours: 11,
    averageIntensity: 'fuerte',
    usageStats: { day: 20, night: 80, summer: 15, winter: 85, office: 15, date: 70 },
    imageUrl: 'https://images.unsplash.com/photo-1467646208740-18124b37eb58?auto=format&fit=crop&w=900&q=80',
    backgroundTheme: 'dark-leather',
    primaryColorHex: '#0f172a',
    secondaryColorHex: '#1f2937',
    buyLinks: [
      { label: 'Ver en tienda A', url: 'https://example.com/midnight-leather' },
      { label: 'Ver en tienda B', url: 'https://example.com/midnight-leather-2' },
    ],
  },
  {
    id: 'p8',
    name: 'Tropical Bloom',
    brand: 'Sol y Mar',
    year: 2024,
    concentration: 'EDP',
    family: 'tropical floral',
    notes: {
      top: ['piña', 'mango', 'papaya'],
      heart: ['tiaré', 'ylang-ylang', 'jazmin'],
      base: ['coco cremoso', 'almizcle suave', 'vainilla ligera'],
    },
    tags: ['tropical', 'frutal', 'coco', 'verano', 'playa', 'dia'],
    summary: 'Frutas jugosas con flores solares y coco cremoso tipo playa.',
    averageRating: 4.5,
    ratingCount: 310,
    averageLongevityHours: 7,
    averageIntensity: 'media',
    usageStats: { day: 88, night: 12, summer: 90, winter: 10, office: 30, date: 55 },
    imageUrl: 'https://images.unsplash.com/photo-1506617420156-8e4536971650?auto=format&fit=crop&w=900&q=80&sat=10',
    backgroundTheme: 'tropical-green',
    primaryColorHex: '#10b981',
    secondaryColorHex: '#f59e0b',
    buyLinks: [
      { label: 'Ver en tienda A', url: 'https://example.com/tropical-bloom' },
      { label: 'Ver en tienda B', url: 'https://example.com/tropical-bloom-2' },
    ],
  },
  {
    id: 'p9',
    name: 'Coastal Breeze',
    brand: 'Blue Current',
    year: 2020,
    concentration: 'EDT',
    family: 'fresco ozonico',
    notes: {
      top: ['limon', 'bergamota', 'pepino'],
      heart: ['notas ozonicas', 'hojas de te', 'jazmin'],
      base: ['almizcle limpio', 'cedro claro'],
    },
    tags: ['ozonico', 'limpio', 'acuatico', 'dia', 'oficina', 'primavera'],
    summary: 'Brisa marina con pepino frio y te verde refrescante.',
    averageRating: 4.1,
    ratingCount: 210,
    averageLongevityHours: 5.5,
    averageIntensity: 'media',
    usageStats: { day: 92, night: 8, summer: 78, winter: 22, office: 80, date: 35 },
    imageUrl: 'https://images.unsplash.com/photo-1515377905703-c4788e51af15?auto=format&fit=crop&w=900&q=80',
    backgroundTheme: 'aquatic-blue',
    primaryColorHex: '#38bdf8',
    secondaryColorHex: '#0ea5e9',
    buyLinks: [
      { label: 'Ver en tienda A', url: 'https://example.com/coastal-breeze' },
      { label: 'Ver en tienda B', url: 'https://example.com/coastal-breeze-2' },
    ],
  },
  {
    id: 'p10',
    name: 'Forest Whisper',
    brand: 'Terra Firma',
    year: 2018,
    concentration: 'EDP',
    family: 'amaderado verde',
    notes: {
      top: ['salvia', 'hojas de higuera'],
      heart: ['vetiver', 'cipres', 'cedro'],
      base: ['musgo de roble', 'ambar ligero'],
    },
    tags: ['amaderado', 'verde', 'bosque', 'otoño', 'senderismo', 'unisex'],
    summary: 'Vetiver terroso con hojas verdes y aire de bosque.',
    averageRating: 4.2,
    ratingCount: 240,
    averageLongevityHours: 8,
    averageIntensity: 'fuerte',
    usageStats: { day: 70, night: 30, summer: 45, winter: 55, office: 50, date: 45 },
    imageUrl: 'https://images.unsplash.com/photo-1506617420156-8e4536971650?auto=format&fit=crop&w=900&q=80&h=900',
    backgroundTheme: 'woody-brown',
    primaryColorHex: '#14532d',
    secondaryColorHex: '#43302e',
    buyLinks: [
      { label: 'Ver en tienda A', url: 'https://example.com/forest-whisper' },
      { label: 'Ver en tienda B', url: 'https://example.com/forest-whisper-2' },
    ],
  },
  {
    id: 'p11',
    name: 'Amber Dusk',
    brand: 'Noctis',
    year: 2022,
    concentration: 'EDP',
    family: 'ambar floral',
    notes: {
      top: ['mandarina', 'azafran'],
      heart: ['rosa', 'almendra', 'heliotropo'],
      base: ['ambar', 'sandalwood', 'vainilla'],
    },
    tags: ['ambar', 'dulce', 'noche', 'otoño', 'invierno', 'romantico'],
    summary: 'Ambar cremoso con rosa almendrada, envolvente y dulce.',
    averageRating: 4.6,
    ratingCount: 370,
    averageLongevityHours: 9,
    averageIntensity: 'fuerte',
    usageStats: { day: 35, night: 65, summer: 30, winter: 70, office: 30, date: 75 },
    imageUrl: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=900&q=80',
    backgroundTheme: 'gourmand-warm',
    primaryColorHex: '#b45309',
    secondaryColorHex: '#f59e0b',
    buyLinks: [
      { label: 'Ver en tienda A', url: 'https://example.com/amber-dusk' },
      { label: 'Ver en tienda B', url: 'https://example.com/amber-dusk-2' },
    ],
  },
  {
    id: 'p12',
    name: 'Sakura Petals',
    brand: 'Hanami',
    year: 2023,
    concentration: 'EDT',
    family: 'floral musgoso',
    notes: {
      top: ['pera', 'lychee'],
      heart: ['flor de cerezo', 'peonia', 'rosa'],
      base: ['almizcle blanco', 'cedro claro'],
    },
    tags: ['floral', 'primavera', 'dia', 'suave', 'romantico', 'casual'],
    summary: 'Floral rosado y algodonoso con peonia y cerezo.',
    averageRating: 4.1,
    ratingCount: 190,
    averageLongevityHours: 5,
    averageIntensity: 'suave',
    usageStats: { day: 90, night: 10, summer: 65, winter: 35, office: 70, date: 55 },
    imageUrl: 'https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=900&q=80',
    backgroundTheme: 'floral-pink',
    primaryColorHex: '#f472b6',
    secondaryColorHex: '#ec4899',
    buyLinks: [
      { label: 'Ver en tienda A', url: 'https://example.com/sakura-petals' },
      { label: 'Ver en tienda B', url: 'https://example.com/sakura-petals-2' },
    ],
  },
  {
    id: 'p13',
    name: 'Spiced Voyage',
    brand: 'Navigator',
    year: 2019,
    concentration: 'EDP',
    family: 'especiado amaderado',
    notes: {
      top: ['pimienta negra', 'cardamomo', 'bayas rosadas'],
      heart: ['incienso', 'geranio', 'cedro'],
      base: ['vetiver', 'ambar', 'patchouli'],
    },
    tags: ['especiado', 'viajero', 'invierno', 'noche', 'aventura', 'unisex'],
    summary: 'Especias secas con vetiver ahumado y resinas viajeras.',
    averageRating: 4.3,
    ratingCount: 245,
    averageLongevityHours: 8,
    averageIntensity: 'fuerte',
    usageStats: { day: 45, night: 55, summer: 35, winter: 65, office: 40, date: 55 },
    imageUrl: 'https://images.unsplash.com/photo-1524592094714-0f0654e20314?auto=format&fit=crop&w=900&q=80&blur=0',
    backgroundTheme: 'woody-brown',
    primaryColorHex: '#8b5a2b',
    secondaryColorHex: '#3f2e1d',
    buyLinks: [
      { label: 'Ver en tienda A', url: 'https://example.com/spiced-voyage' },
      { label: 'Ver en tienda B', url: 'https://example.com/spiced-voyage-2' },
    ],
  },
  {
    id: 'p14',
    name: 'Pure Cotton',
    brand: 'Clean Lab',
    year: 2020,
    concentration: 'Cologne',
    family: 'almizcle limpio',
    notes: {
      top: ['aldehidos', 'limon suave'],
      heart: ['algodon', 'iris', 'jazmin'],
      base: ['almizcle blanco', 'ambar ligero'],
    },
    tags: ['limpio', 'algodon', 'jabonoso', 'dia', 'oficina', 'minimalista'],
    summary: 'Sensacion de ropa recien lavada con almizcle blanco.',
    averageRating: 4.0,
    ratingCount: 180,
    averageLongevityHours: 4.5,
    averageIntensity: 'suave',
    usageStats: { day: 95, night: 5, summer: 70, winter: 30, office: 90, date: 25 },
    imageUrl: 'https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=900&q=80&sat=-20',
    backgroundTheme: 'clean-blue',
    primaryColorHex: '#e0f2fe',
    secondaryColorHex: '#93c5fd',
    buyLinks: [
      { label: 'Ver en tienda A', url: 'https://example.com/pure-cotton' },
      { label: 'Ver en tienda B', url: 'https://example.com/pure-cotton-2' },
    ],
  },
  {
    id: 'p15',
    name: 'Vanilla Smoke',
    brand: 'Obscura',
    year: 2021,
    concentration: 'Parfum',
    family: 'gourmand ahumado',
    notes: {
      top: ['vainilla bourbon', 'tabaco blond'],
      heart: ['humo suave', 'cedro'],
      base: ['benjui', 'tonka', 'almizcle'],
    },
    tags: ['gourmand', 'dulce', 'ahumado', 'noche', 'invierno', 'cozy'],
    summary: 'Vainilla oscura con tabaco meloso y humo elegante.',
    averageRating: 4.7,
    ratingCount: 310,
    averageLongevityHours: 10,
    averageIntensity: 'fuerte',
    usageStats: { day: 25, night: 75, summer: 15, winter: 85, office: 25, date: 70 },
    imageUrl: 'https://images.unsplash.com/photo-1524592094714-0f0654e20314?auto=format&fit=crop&w=900&q=80&sat=20',
    backgroundTheme: 'gourmand-warm',
    primaryColorHex: '#b45309',
    secondaryColorHex: '#7c2d12',
    buyLinks: [
      { label: 'Ver en tienda A', url: 'https://example.com/vanilla-smoke' },
      { label: 'Ver en tienda B', url: 'https://example.com/vanilla-smoke-2' },
    ],
  },
  {
    id: 'p16',
    name: 'Rainy City',
    brand: 'Metro',
    year: 2022,
    concentration: 'EDT',
    family: 'acuatico metalico',
    notes: {
      top: ['pepino', 'aldehidos', 'lima'],
      heart: ['violeta', 'notas metalicas', 'iris'],
      base: ['ambar gris', 'maderas claras'],
    },
    tags: ['urbano', 'lluvia', 'acuatico', 'oficina', 'dia', 'unisex'],
    summary: 'Bruma humeda de ciudad con violeta y notas metalicas frescas.',
    averageRating: 4.1,
    ratingCount: 150,
    averageLongevityHours: 6,
    averageIntensity: 'media',
    usageStats: { day: 85, night: 15, summer: 65, winter: 35, office: 85, date: 35 },
    imageUrl: 'https://images.unsplash.com/photo-1506617420156-8e4536971650?auto=format&fit=crop&w=900&q=80&sat=-10',
    backgroundTheme: 'aquatic-blue',
    primaryColorHex: '#0ea5e9',
    secondaryColorHex: '#64748b',
    buyLinks: [
      { label: 'Ver en tienda A', url: 'https://example.com/rainy-city' },
      { label: 'Ver en tienda B', url: 'https://example.com/rainy-city-2' },
    ],
  },
  {
    id: 'p17',
    name: 'Golden Neroli',
    brand: 'Citrus Atelier',
    year: 2023,
    concentration: 'EDP',
    family: 'citrico floral',
    notes: {
      top: ['neroli', 'petitgrain', 'limon'],
      heart: ['azahar', 'flor de limonero'],
      base: ['almizcle', 'maderas claras'],
    },
    tags: ['neroli', 'citrico', 'floral blanco', 'primavera', 'dia', 'oficina'],
    summary: 'Neroli luminoso con flores de azahar y base limpia.',
    averageRating: 4.4,
    ratingCount: 260,
    averageLongevityHours: 7,
    averageIntensity: 'media',
    usageStats: { day: 92, night: 8, summer: 80, winter: 20, office: 75, date: 50 },
    imageUrl: 'https://images.unsplash.com/photo-1524592094714-0f0654e20314?auto=format&fit=crop&w=900&q=80&sat=30',
    backgroundTheme: 'citrus-yellow',
    primaryColorHex: '#f59e0b',
    secondaryColorHex: '#facc15',
    buyLinks: [
      { label: 'Ver en tienda A', url: 'https://example.com/golden-neroli' },
      { label: 'Ver en tienda B', url: 'https://example.com/golden-neroli-2' },
    ],
  },
  {
    id: 'p18',
    name: 'Cafe Nocturno',
    brand: 'Barista Parfums',
    year: 2021,
    concentration: 'EDP',
    family: 'gourmand cafe',
    notes: {
      top: ['espresso', 'cardamomo'],
      heart: ['cacao', 'iris'],
      base: ['vainilla', 'sandalwood', 'almizcle'],
    },
    tags: ['cafe', 'gourmand', 'dulce', 'noche', 'otoño', 'invierno'],
    summary: 'Shot de espresso cremoso con cacao y vainilla tostada.',
    averageRating: 4.5,
    ratingCount: 330,
    averageLongevityHours: 8,
    averageIntensity: 'fuerte',
    usageStats: { day: 30, night: 70, summer: 20, winter: 80, office: 25, date: 65 },
    imageUrl: 'https://images.unsplash.com/photo-1481391032119-d89fee407e44?auto=format&fit=crop&w=900&q=80',
    backgroundTheme: 'gourmand-warm',
    primaryColorHex: '#7c2d12',
    secondaryColorHex: '#b45309',
    buyLinks: [
      { label: 'Ver en tienda A', url: 'https://example.com/cafe-nocturno' },
      { label: 'Ver en tienda B', url: 'https://example.com/cafe-nocturno-2' },
    ],
  },
  {
    id: 'p19',
    name: 'Fig Garden',
    brand: 'Hesperia',
    year: 2020,
    concentration: 'EDT',
    family: 'verde frutal',
    notes: {
      top: ['hojas de higuera', 'mandarina'],
      heart: ['higo cremoso', 'coco suave'],
      base: ['cedro', 'almizcle'],
    },
    tags: ['higo', 'verde', 'cremoso', 'dia', 'verano', 'casual'],
    summary: 'Higo lactonico con hojas verdes y coco ligero.',
    averageRating: 4.2,
    ratingCount: 210,
    averageLongevityHours: 6,
    averageIntensity: 'media',
    usageStats: { day: 88, night: 12, summer: 80, winter: 20, office: 60, date: 45 },
    imageUrl: 'https://images.unsplash.com/photo-1524592094714-0f0654e20314?auto=format&fit=crop&w=900&q=80&sat=-5',
    backgroundTheme: 'tropical-green',
    primaryColorHex: '#15803d',
    secondaryColorHex: '#84cc16',
    buyLinks: [
      { label: 'Ver en tienda A', url: 'https://example.com/fig-garden' },
      { label: 'Ver en tienda B', url: 'https://example.com/fig-garden-2' },
    ],
  },
  {
    id: 'p20',
    name: 'Silver Vetiver',
    brand: 'Urban Roots',
    year: 2019,
    concentration: 'EDP',
    family: 'vetiver fresco',
    notes: {
      top: ['toronja', 'jengibre'],
      heart: ['vetiver de haiti', 'iris'],
      base: ['ambar gris', 'almizcle'],
    },
    tags: ['vetiver', 'amaderado', 'verde', 'oficina', 'dia', 'minimalista'],
    summary: 'Vetiver brillante con toronja amarga e iris polvoso.',
    averageRating: 4.3,
    ratingCount: 260,
    averageLongevityHours: 7,
    averageIntensity: 'media',
    usageStats: { day: 85, night: 15, summer: 65, winter: 35, office: 85, date: 45 },
    imageUrl: 'https://images.unsplash.com/photo-1506617420156-8e4536971650?auto=format&fit=crop&w=900&q=80&sat=15',
    backgroundTheme: 'woody-brown',
    primaryColorHex: '#0f766e',
    secondaryColorHex: '#0ea5e9',
    buyLinks: [
      { label: 'Ver en tienda A', url: 'https://example.com/silver-vetiver' },
      { label: 'Ver en tienda B', url: 'https://example.com/silver-vetiver-2' },
    ],
  },
  {
    id: 'p21',
    name: 'Rose Atelier',
    brand: 'Atelier Fleurs',
    year: 2023,
    concentration: 'EDP',
    family: 'floral rosado',
    notes: {
      top: ['lichi', 'pimienta rosa'],
      heart: ['rosa centifolia', 'peonia'],
      base: ['cashmere', 'almizcle'],
    },
    tags: ['rosa', 'floral', 'romantico', 'dia', 'primavera', 'cita'],
    summary: 'Rosa jugosa con peonia y fondo de cashmere reconfortante.',
    averageRating: 4.5,
    ratingCount: 300,
    averageLongevityHours: 7,
    averageIntensity: 'media',
    usageStats: { day: 85, night: 15, summer: 70, winter: 30, office: 60, date: 80 },
    imageUrl: 'https://images.unsplash.com/photo-1524592094714-0f0654e20314?auto=format&fit=crop&w=900&q=80&sat=40',
    backgroundTheme: 'floral-pink',
    primaryColorHex: '#ec4899',
    secondaryColorHex: '#f472b6',
    buyLinks: [
      { label: 'Ver en tienda A', url: 'https://example.com/rose-atelier' },
      { label: 'Ver en tienda B', url: 'https://example.com/rose-atelier-2' },
    ],
  },
  {
    id: 'p22',
    name: 'Ocean Driftwood',
    brand: 'Tidecraft',
    year: 2021,
    concentration: 'EDT',
    family: 'acuatico amaderado',
    notes: {
      top: ['sal marina', 'limon', 'hojas de shiso'],
      heart: ['driftwood', 'violeta', 'te verde'],
      base: ['cedro', 'almizcle limpio', 'ambar gris'],
    },
    tags: ['marino', 'maderas claras', 'verano', 'dia', 'casual', 'surfer'],
    summary: 'Maderas claras bañadas por sal marina y brisa herbal.',
    averageRating: 4.2,
    ratingCount: 210,
    averageLongevityHours: 6,
    averageIntensity: 'media',
    usageStats: { day: 90, night: 10, summer: 85, winter: 15, office: 55, date: 40 },
    imageUrl: 'https://images.unsplash.com/photo-1506617420156-8e4536971650?auto=format&fit=crop&w=900&q=80&sat=-15',
    backgroundTheme: 'aquatic-blue',
    primaryColorHex: '#0284c7',
    secondaryColorHex: '#14b8a6',
    buyLinks: [
      { label: 'Ver en tienda A', url: 'https://example.com/ocean-driftwood' },
      { label: 'Ver en tienda B', url: 'https://example.com/ocean-driftwood-2' },
    ],
  },
  {
    id: 'p23',
    name: 'Amber Saffron',
    brand: 'Maison Dore',
    year: 2020,
    concentration: 'EDP',
    family: 'ambar especiado',
    notes: {
      top: ['azafran', 'jazmin'],
      heart: ['ambre gris', 'resinas'],
      base: ['cedro', 'vainilla', 'sandalwood'],
    },
    tags: ['ambar', 'azafran', 'dulce', 'noche', 'otoño', 'lujoso'],
    summary: 'Azafran luminoso con ambar salado y madera cremosa.',
    averageRating: 4.7,
    ratingCount: 500,
    averageLongevityHours: 11,
    averageIntensity: 'fuerte',
    usageStats: { day: 30, night: 70, summer: 30, winter: 70, office: 35, date: 80 },
    imageUrl: 'https://images.unsplash.com/photo-1506617420156-8e4536971650?auto=format&fit=crop&w=900&q=80&sat=5',
    backgroundTheme: 'gourmand-warm',
    primaryColorHex: '#d97706',
    secondaryColorHex: '#92400e',
    buyLinks: [
      { label: 'Ver en tienda A', url: 'https://example.com/amber-saffron' },
      { label: 'Ver en tienda B', url: 'https://example.com/amber-saffron-2' },
    ],
  },
  {
    id: 'p24',
    name: 'Green Tea Cloud',
    brand: 'Zen Atelier',
    year: 2018,
    concentration: 'EDT',
    family: 'te verde',
    notes: {
      top: ['te verde', 'limon', 'menta'],
      heart: ['jazmin', 'mate', 'violeta'],
      base: ['almizcle blanco', 'cedro'],
    },
    tags: ['te verde', 'limpio', 'dia', 'verano', 'oficina', 'relax'],
    summary: 'Nube ligera de te verde con jazmin y almizcle limpio.',
    averageRating: 4.1,
    ratingCount: 260,
    averageLongevityHours: 5,
    averageIntensity: 'suave',
    usageStats: { day: 95, night: 5, summer: 85, winter: 15, office: 85, date: 30 },
    imageUrl: 'https://images.unsplash.com/photo-1481391032119-d89fee407e44?auto=format&fit=crop&w=900&q=80&sat=-15',
    backgroundTheme: 'clean-blue',
    primaryColorHex: '#bbf7d0',
    secondaryColorHex: '#22c55e',
    buyLinks: [
      { label: 'Ver en tienda A', url: 'https://example.com/green-tea-cloud' },
      { label: 'Ver en tienda B', url: 'https://example.com/green-tea-cloud-2' },
    ],
  },
  {
    id: 'p25',
    name: 'Blue Horizon',
    brand: 'Skyline',
    year: 2022,
    concentration: 'EDT',
    family: 'aromatico fresco',
    notes: {
      top: ['pomelo', 'menta', 'aldehidos'],
      heart: ['lavanda', 'salvia', 'piña'],
      base: ['sandalwood', 'cedro', 'ambar gris'],
    },
    tags: ['fresco', 'aromatico', 'verano', 'dia', 'deportivo', 'oficina'],
    summary: 'Aromatico deportivo con pomelo chispeante y madera clara.',
    averageRating: 4.0,
    ratingCount: 205,
    averageLongevityHours: 6,
    averageIntensity: 'media',
    usageStats: { day: 90, night: 10, summer: 75, winter: 25, office: 70, date: 35 },
    imageUrl: 'https://images.unsplash.com/photo-1515377905703-c4788e51af15?auto=format&fit=crop&w=900&q=80&sat=-10',
    backgroundTheme: 'aquatic-blue',
    primaryColorHex: '#3b82f6',
    secondaryColorHex: '#06b6d4',
    buyLinks: [
      { label: 'Ver en tienda A', url: 'https://example.com/blue-horizon' },
      { label: 'Ver en tienda B', url: 'https://example.com/blue-horizon-2' },
    ],
  },
  {
    id: 'p26',
    name: 'Fireside Cedar',
    brand: 'Hearth',
    year: 2019,
    concentration: 'EDP',
    family: 'amaderado ahumado',
    notes: {
      top: ['pimienta', 'manzana roja'],
      heart: ['cedro', 'cachemira', 'incienso'],
      base: ['ambar', 'haba tonka', 'maderas tostadas'],
    },
    tags: ['cedro', 'ahumado', 'invierno', 'noche', 'hogar', 'calido'],
    summary: 'Maderas tostadas junto a una chimenea con cedro resinoso.',
    averageRating: 4.3,
    ratingCount: 230,
    averageLongevityHours: 9,
    averageIntensity: 'fuerte',
    usageStats: { day: 35, night: 65, summer: 25, winter: 75, office: 25, date: 60 },
    imageUrl: 'https://images.unsplash.com/photo-1506617420156-8e4536971650?auto=format&fit=crop&w=900&q=80&sat=-25',
    backgroundTheme: 'woody-brown',
    primaryColorHex: '#78350f',
    secondaryColorHex: '#111827',
    buyLinks: [
      { label: 'Ver en tienda A', url: 'https://example.com/fireside-cedar' },
      { label: 'Ver en tienda B', url: 'https://example.com/fireside-cedar-2' },
    ],
  },
  {
    id: 'p27',
    name: 'Orchard Sunrise',
    brand: 'Fruite',
    year: 2024,
    concentration: 'EDT',
    family: 'frutal floral',
    notes: {
      top: ['manzana verde', 'pera', 'mandarina'],
      heart: ['flor de azahar', 'rosa suave'],
      base: ['almizcle', 'santal claro'],
    },
    tags: ['frutal', 'floral', 'dia', 'primavera', 'alegre', 'casual'],
    summary: 'Frutas jugosas con azahar y fondo de santal cremoso.',
    averageRating: 4.1,
    ratingCount: 190,
    averageLongevityHours: 6,
    averageIntensity: 'media',
    usageStats: { day: 93, night: 7, summer: 75, winter: 25, office: 70, date: 45 },
    imageUrl: 'https://images.unsplash.com/photo-1498842812179-c81beecf902c?auto=format&fit=crop&w=900&q=80&sat=5',
    backgroundTheme: 'tropical-green',
    primaryColorHex: '#84cc16',
    secondaryColorHex: '#f97316',
    buyLinks: [
      { label: 'Ver en tienda A', url: 'https://example.com/orchard-sunrise' },
      { label: 'Ver en tienda B', url: 'https://example.com/orchard-sunrise-2' },
    ],
  },
  {
    id: 'p28',
    name: 'Night Iris',
    brand: 'Nocturna',
    year: 2018,
    concentration: 'EDP',
    family: 'floral atalcado',
    notes: {
      top: ['bergamota', 'pimienta rosa'],
      heart: ['iris', 'violeta', 'heliotropo'],
      base: ['sandalwood', 'almizcle', 'vainilla ligera'],
    },
    tags: ['iris', 'atalcado', 'suave', 'noche', 'elegante', 'invierno'],
    summary: 'Iris empolvado con santal cremoso y vainilla sutil.',
    averageRating: 4.4,
    ratingCount: 260,
    averageLongevityHours: 8,
    averageIntensity: 'media',
    usageStats: { day: 45, night: 55, summer: 25, winter: 75, office: 40, date: 70 },
    imageUrl: 'https://images.unsplash.com/photo-1489515217757-5fd1be406fef?auto=format&fit=crop&w=900&q=80&sat=25',
    backgroundTheme: 'floral-pink',
    primaryColorHex: '#a855f7',
    secondaryColorHex: '#7c3aed',
    buyLinks: [
      { label: 'Ver en tienda A', url: 'https://example.com/night-iris' },
      { label: 'Ver en tienda B', url: 'https://example.com/night-iris-2' },
    ],
  },
  {
    id: 'p29',
    name: 'White Musk',
    brand: 'Pure Skin',
    year: 2022,
    concentration: 'EDT',
    family: 'almizcle limpio',
    notes: {
      top: ['aldehidos', 'peonia suave'],
      heart: ['almizcle blanco', 'iris'],
      base: ['santal claro', 'ambar ligero'],
    },
    tags: ['almizcle', 'limpio', 'minimalista', 'dia', 'oficina', 'suave'],
    summary: 'Musk algodonoso con toque de peonia e iris.',
    averageRating: 4.0,
    ratingCount: 175,
    averageLongevityHours: 5,
    averageIntensity: 'suave',
    usageStats: { day: 96, night: 4, summer: 70, winter: 30, office: 90, date: 30 },
    imageUrl: 'https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=900&q=80&sat=-30',
    backgroundTheme: 'clean-blue',
    primaryColorHex: '#e2e8f0',
    secondaryColorHex: '#cbd5e1',
    buyLinks: [
      { label: 'Ver en tienda A', url: 'https://example.com/white-musk' },
      { label: 'Ver en tienda B', url: 'https://example.com/white-musk-2' },
    ],
  },
  {
    id: 'p30',
    name: 'Sandal Serenity',
    brand: 'Calma',
    year: 2019,
    concentration: 'EDP',
    family: 'amaderado cremoso',
    notes: {
      top: ['cardamomo suave', 'lima'],
      heart: ['sandalwood lactonico', 'iris'],
      base: ['almizcle', 'vainilla ligera'],
    },
    tags: ['sandalwood', 'cremoso', 'zen', 'dia', 'oficina', 'relajante'],
    summary: 'Santal cremoso y lactonico con iris sedoso.',
    averageRating: 4.3,
    ratingCount: 240,
    averageLongevityHours: 8,
    averageIntensity: 'media',
    usageStats: { day: 85, night: 15, summer: 55, winter: 45, office: 80, date: 45 },
    imageUrl: 'https://images.unsplash.com/photo-1489515217757-5fd1be406fef?auto=format&fit=crop&w=900&q=80&sat=-5',
    backgroundTheme: 'woody-brown',
    primaryColorHex: '#b45309',
    secondaryColorHex: '#f59e0b',
    buyLinks: [
      { label: 'Ver en tienda A', url: 'https://example.com/sandal-serenity' },
      { label: 'Ver en tienda B', url: 'https://example.com/sandal-serenity-2' },
    ],
  },
  {
    id: 'p31',
    name: 'Urban Oud',
    brand: 'Concrete',
    year: 2022,
    concentration: 'Parfum',
    family: 'oud moderno',
    notes: {
      top: ['azafran', 'manzana'],
      heart: ['oud refinado', 'rosa', 'cedro'],
      base: ['musk', 'ambar', 'vainilla ligera'],
    },
    tags: ['oud', 'urban', 'moderno', 'noche', 'invierno', 'formal'],
    summary: 'Oud pulido con azafran y frutas rojas en ambiente urbano.',
    averageRating: 4.6,
    ratingCount: 320,
    averageLongevityHours: 11,
    averageIntensity: 'fuerte',
    usageStats: { day: 25, night: 75, summer: 25, winter: 75, office: 20, date: 80 },
    imageUrl: 'https://images.unsplash.com/photo-1506617420156-8e4536971650?auto=format&fit=crop&w=900&q=80&sat=-35',
    backgroundTheme: 'dark-leather',
    primaryColorHex: '#111827',
    secondaryColorHex: '#6b21a8',
    buyLinks: [
      { label: 'Ver en tienda A', url: 'https://example.com/urban-oud' },
      { label: 'Ver en tienda B', url: 'https://example.com/urban-oud-2' },
    ],
  },
  {
    id: 'p32',
    name: 'Aurora Boreal',
    brand: 'Polar Lights',
    year: 2024,
    concentration: 'EDP',
    family: 'fresco aromatico',
    notes: {
      top: ['menta helada', 'limon', 'aldehidos frios'],
      heart: ['abeto', 'lavanda', 'romero'],
      base: ['almizcle blanco', 'ambergris'],
    },
    tags: ['frio', 'menta', 'acuatico', 'noche', 'invierno', 'unisex'],
    summary: 'Luz fria con menta helada y pino cristalino.',
    averageRating: 4.2,
    ratingCount: 180,
    averageLongevityHours: 7,
    averageIntensity: 'media',
    usageStats: { day: 55, night: 45, summer: 35, winter: 65, office: 50, date: 50 },
    imageUrl: 'https://images.unsplash.com/photo-1500375592092-40eb2168fd21?auto=format&fit=crop&w=900&q=80',
    backgroundTheme: 'aquatic-blue',
    primaryColorHex: '#0ea5e9',
    secondaryColorHex: '#7dd3fc',
    buyLinks: [
      { label: 'Ver en tienda A', url: 'https://example.com/aurora-boreal' },
      { label: 'Ver en tienda B', url: 'https://example.com/aurora-boreal-2' },
    ],
  },
  {
    id: 'p33',
    name: 'Lavender Fields',
    brand: 'Provence',
    year: 2019,
    concentration: 'EDT',
    family: 'aromatico lavanda',
    notes: {
      top: ['lavanda', 'limon', 'romero'],
      heart: ['lavanda', 'geranio', 'musgo ligero'],
      base: ['tonka', 'cedro', 'almizcle'],
    },
    tags: ['lavanda', 'herbal', 'campo', 'dia', 'primavera', 'relax'],
    summary: 'Lavanda limpia con limon, romero y tonka cremosa.',
    averageRating: 4.1,
    ratingCount: 210,
    averageLongevityHours: 6,
    averageIntensity: 'media',
    usageStats: { day: 88, night: 12, summer: 70, winter: 30, office: 70, date: 35 },
    imageUrl: 'https://images.unsplash.com/photo-1508257842600-9b59e8361500?auto=format&fit=crop&w=900&q=80',
    backgroundTheme: 'floral-pink',
    primaryColorHex: '#8b5cf6',
    secondaryColorHex: '#6366f1',
    buyLinks: [
      { label: 'Ver en tienda A', url: 'https://example.com/lavender-fields' },
      { label: 'Ver en tienda B', url: 'https://example.com/lavender-fields-2' },
    ],
  },
  {
    id: 'p34',
    name: 'Cocoa Velvet',
    brand: 'Maison Cacao',
    year: 2020,
    concentration: 'Parfum',
    family: 'gourmand cacao',
    notes: {
      top: ['chocolate negro', 'nuez moscada'],
      heart: ['iris', 'cafe suave'],
      base: ['vainilla', 'sandalwood', 'caramelo'],
    },
    tags: ['cacao', 'gourmand', 'dulce', 'invierno', 'noche', 'postre'],
    summary: 'Cacao oscuro aterciopelado con iris y caramelo dorado.',
    averageRating: 4.6,
    ratingCount: 275,
    averageLongevityHours: 9,
    averageIntensity: 'fuerte',
    usageStats: { day: 25, night: 75, summer: 15, winter: 85, office: 25, date: 70 },
    imageUrl: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&w=900&q=80',
    backgroundTheme: 'gourmand-warm',
    primaryColorHex: '#92400e',
    secondaryColorHex: '#c2410c',
    buyLinks: [
      { label: 'Ver en tienda A', url: 'https://example.com/cocoa-velvet' },
      { label: 'Ver en tienda B', url: 'https://example.com/cocoa-velvet-2' },
    ],
  },
  {
    id: 'p35',
    name: 'Citrus Gin',
    brand: 'Botanica',
    year: 2021,
    concentration: 'EDT',
    family: 'citrico aromatico',
    notes: {
      top: ['lima', 'pomelo', 'bayas de enebro'],
      heart: ['hojas de gin', 'romero', 'cardamomo'],
      base: ['cedro', 'almizcle limpio'],
    },
    tags: ['citricos', 'enebro', 'coctel', 'verano', 'dia', 'fiesta'],
    summary: 'Gin tonico aromatico con lima y enebro helado.',
    averageRating: 4.0,
    ratingCount: 190,
    averageLongevityHours: 5.5,
    averageIntensity: 'media',
    usageStats: { day: 92, night: 8, summer: 85, winter: 15, office: 55, date: 40 },
    imageUrl: 'https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=900&q=80&sat=15',
    backgroundTheme: 'citrus-yellow',
    primaryColorHex: '#f59e0b',
    secondaryColorHex: '#22c55e',
    buyLinks: [
      { label: 'Ver en tienda A', url: 'https://example.com/citrus-gin' },
      { label: 'Ver en tienda B', url: 'https://example.com/citrus-gin-2' },
    ],
  },
  {
    id: 'p36',
    name: 'Island Mango',
    brand: 'Pacific Soul',
    year: 2023,
    concentration: 'EDP',
    family: 'tropical frutal',
    notes: {
      top: ['mango', 'maracuya'],
      heart: ['frangipani', 'coco cremoso'],
      base: ['almizcle solar', 'vainilla ligera'],
    },
    tags: ['mango', 'tropical', 'dulce', 'verano', 'playa', 'dia'],
    summary: 'Mango jugoso con coco cremoso y vainilla solar.',
    averageRating: 4.4,
    ratingCount: 250,
    averageLongevityHours: 7,
    averageIntensity: 'media',
    usageStats: { day: 90, night: 10, summer: 92, winter: 8, office: 30, date: 60 },
    imageUrl: 'https://images.unsplash.com/photo-1506617420156-8e4536971650?auto=format&fit=crop&w=900&q=80&sat=25',
    backgroundTheme: 'tropical-green',
    primaryColorHex: '#22c55e',
    secondaryColorHex: '#f97316',
    buyLinks: [
      { label: 'Ver en tienda A', url: 'https://example.com/island-mango' },
      { label: 'Ver en tienda B', url: 'https://example.com/island-mango-2' },
    ],
  },
  {
    id: 'p37',
    name: 'Smoky Tobacco',
    brand: 'Havana Nights',
    year: 2020,
    concentration: 'EDP',
    family: 'tabaco ahumado',
    notes: {
      top: ['miel', 'ciruela seca'],
      heart: ['tabaco', 'cuero suave'],
      base: ['haba tonka', 'vainilla', 'maderas ahumadas'],
    },
    tags: ['tabaco', 'cuero', 'ahumado', 'noche', 'otoño', 'invierno'],
    summary: 'Tabaco dulce con miel y humo elegante de madera.',
    averageRating: 4.5,
    ratingCount: 330,
    averageLongevityHours: 10,
    averageIntensity: 'fuerte',
    usageStats: { day: 20, night: 80, summer: 15, winter: 85, office: 20, date: 70 },
    imageUrl: 'https://images.unsplash.com/photo-1489515217757-5fd1be406fef?auto=format&fit=crop&w=900&q=80&sat=-15',
    backgroundTheme: 'dark-leather',
    primaryColorHex: '#3f3f46',
    secondaryColorHex: '#f59e0b',
    buyLinks: [
      { label: 'Ver en tienda A', url: 'https://example.com/smoky-tobacco' },
      { label: 'Ver en tienda B', url: 'https://example.com/smoky-tobacco-2' },
    ],
  },
  {
    id: 'p38',
    name: 'Ginger Spark',
    brand: 'Voltage',
    year: 2021,
    concentration: 'EDT',
    family: 'especiado fresco',
    notes: {
      top: ['jengibre', 'limon', 'cardamomo'],
      heart: ['elemi', 'te verde', 'geranio'],
      base: ['cedro', 'almizcle'],
    },
    tags: ['jengibre', 'fresco', 'chispeante', 'dia', 'verano', 'oficina'],
    summary: 'Jengibre electrico con limon y maderas claras limpias.',
    averageRating: 4.0,
    ratingCount: 185,
    averageLongevityHours: 6,
    averageIntensity: 'media',
    usageStats: { day: 93, night: 7, summer: 80, winter: 20, office: 78, date: 40 },
    imageUrl: 'https://images.unsplash.com/photo-1506617420156-8e4536971650?auto=format&fit=crop&w=900&q=80&sat=35',
    backgroundTheme: 'citrus-yellow',
    primaryColorHex: '#fbbf24',
    secondaryColorHex: '#f59e0b',
    buyLinks: [
      { label: 'Ver en tienda A', url: 'https://example.com/ginger-spark' },
      { label: 'Ver en tienda B', url: 'https://example.com/ginger-spark-2' },
    ],
  },
  {
    id: 'p39',
    name: 'Arctic Mint',
    brand: 'Glacier',
    year: 2022,
    concentration: 'EDT',
    family: 'menta helada',
    notes: {
      top: ['menta polar', 'limon', 'eucalipto'],
      heart: ['lavanda', 'romero', 'abeto'],
      base: ['almizcle azul', 'cedro helado'],
    },
    tags: ['menta', 'fresco', 'frio', 'verano', 'dia', 'deportivo'],
    summary: 'Explosión mentolada helada con pino y limon brillante.',
    averageRating: 4.1,
    ratingCount: 170,
    averageLongevityHours: 6,
    averageIntensity: 'media',
    usageStats: { day: 94, night: 6, summer: 88, winter: 12, office: 60, date: 30 },
    imageUrl: 'https://images.unsplash.com/photo-1500375592092-40eb2168fd21?auto=format&fit=crop&w=900&q=80&sat=-5',
    backgroundTheme: 'aquatic-blue',
    primaryColorHex: '#0ea5e9',
    secondaryColorHex: '#14b8a6',
    buyLinks: [
      { label: 'Ver en tienda A', url: 'https://example.com/arctic-mint' },
      { label: 'Ver en tienda B', url: 'https://example.com/arctic-mint-2' },
    ],
  },
  {
    id: 'p40',
    name: 'Desert Bloom',
    brand: 'Oasis',
    year: 2021,
    concentration: 'EDP',
    family: 'floral ambarado',
    notes: {
      top: ['azahar', 'mandarina'],
      heart: ['tuberosa', 'ylang-ylang', 'jazmin'],
      base: ['ambar dorado', 'vainilla', 'sandalwood'],
    },
    tags: ['floral blanco', 'ambar', 'tropical', 'noche', 'verano', 'cita'],
    summary: 'Flor blanca cremosa envuelta en ambar dorado calido.',
    averageRating: 4.4,
    ratingCount: 260,
    averageLongevityHours: 9,
    averageIntensity: 'fuerte',
    usageStats: { day: 35, night: 65, summer: 75, winter: 25, office: 30, date: 80 },
    imageUrl: 'https://images.unsplash.com/photo-1524592094714-0f0654e20314?auto=format&fit=crop&w=900&q=80&sat=15',
    backgroundTheme: 'gourmand-warm',
    primaryColorHex: '#d97706',
    secondaryColorHex: '#854d0e',
    buyLinks: [
      { label: 'Ver en tienda A', url: 'https://example.com/desert-bloom' },
      { label: 'Ver en tienda B', url: 'https://example.com/desert-bloom-2' },
    ],
  },
];

const preferencesByUser: Record<string, UserPreferences> = {
  'user-1': {
    userId: 'user-1',
    likes: ['p1', 'p3', 'p4', 'p8', 'p12', 'p20'],
    dislikes: ['p18'],
    favorites: ['p1', 'p4', 'p9'],
    wantToTry: ['p5', 'p38'],
    haveIt: ['p3'],
  },
};

const reviews: UserReview[] = [
  { userId: 'user-1', perfumeId: 'p1', rating: 4, comment: 'Fresco y facil de usar', createdAt: new Date() },
  { userId: 'user-2', perfumeId: 'p2', rating: 5, comment: 'Intenso y elegante', createdAt: new Date() },
  { userId: 'user-3', perfumeId: 'p9', rating: 5, comment: 'Ambarado profundo para noches frias', createdAt: new Date() },
  { userId: 'user-4', perfumeId: 'p12', rating: 4, comment: 'Tropical divertido, ideal verano', createdAt: new Date() },
];

function ensureUserPreferences(userId: string): UserPreferences {
  if (!preferencesByUser[userId]) {
    preferencesByUser[userId] = { userId, likes: [], dislikes: [], favorites: [], wantToTry: [], haveIt: [] };
  }
  return preferencesByUser[userId];
}

function toggleInList(list: string[], perfumeId: string) {
  const exists = list.includes(perfumeId);
  if (exists) {
    return list.filter((id) => id !== perfumeId);
  }
  return [...list, perfumeId];
}

const actionMap: Record<PreferenceAction, keyof UserPreferences> = {
  like: 'likes',
  dislike: 'dislikes',
  favorite: 'favorites',
  wantToTry: 'wantToTry',
  haveIt: 'haveIt',
};

function applyPreferenceAction(userId: string, perfumeId: string, action: PreferenceAction): UserPreferences {
  const prefs = ensureUserPreferences(userId);
  const targetKey = actionMap[action];
  if (action === 'like') {
    prefs.dislikes = prefs.dislikes.filter((id) => id !== perfumeId);
  }
  if (action === 'dislike') {
    prefs.likes = prefs.likes.filter((id) => id !== perfumeId);
  }
  prefs[targetKey] = toggleInList(prefs[targetKey], perfumeId);
  return prefs;
}

export const perfumeService = {
  listPerfumes: (filters?: { name?: string; brand?: string; tag?: string }) => {
    const nameTerm = filters?.name?.toLowerCase() || '';
    const brandTerm = filters?.brand?.toLowerCase() || '';
    const tagTerm = filters?.tag?.toLowerCase() || '';

    return perfumes.filter((perfume) => {
      const matchesName = !nameTerm || perfume.name.toLowerCase().includes(nameTerm);
      const matchesBrand = !brandTerm || perfume.brand.toLowerCase().includes(brandTerm);
      const matchesTag = !tagTerm || perfume.tags.some((tag) => tag.toLowerCase() === tagTerm);
      return matchesName && matchesBrand && matchesTag;
    });
  },

  getPerfumeById: (id: string) => perfumes.find((perfume) => perfume.id === id),
  getAll: () => perfumes,

  getUserPreferences: (userId: string) => ensureUserPreferences(userId),

  updateUserPreference: (userId: string, perfumeId: string, action: PreferenceAction) => {
    return applyPreferenceAction(userId, perfumeId, action);
  },

  getReviewsByPerfume: (perfumeId: string) => reviews.filter((review) => review.perfumeId === perfumeId),

  addReview: (review: Omit<UserReview, 'createdAt'>) => {
    const newReview: UserReview = { ...review, createdAt: new Date() };
    reviews.push(newReview);
    return newReview;
  },
};
