// In-memory data and helpers for perfumes, preferences, and reviews.
import { Perfume, PreferenceAction, UserPreferences, UserReview } from '../models/domain';

const perfumes: Perfume[] = [
  {
    id: 'p1',
    name: 'Citrus Bloom',
    brand: 'Atelier Verde',
    year: 2022,
    concentration: 'EDT',
    family: 'citrico floral',
    notes: { top: ['bergamota', 'limon'], heart: ['neroli', 'petitgrain'], base: ['almizcle'] },
    tags: ['fresco', 'verano', 'dia', 'citrico', 'oficina', 'casual'],
    averageRating: 4.4,
    ratingCount: 240,
    averageLongevityHours: 7,
    averageIntensity: 'media',
    usageStats: { day: 75, night: 25, summer: 80, winter: 20, office: 70, date: 40 },
    imageUrl: 'https://images.unsplash.com/photo-1524592094714-0f0654e20314?auto=format&fit=crop&w=800&q=80',
    backgroundTheme: 'citrus-yellow',
    buyLinks: [
      { label: 'Ver en tienda A', url: 'https://example.com/tienda-a/citrus-bloom' },
      { label: 'Ver en tienda B', url: 'https://example.com/tienda-b/citrus-bloom' },
    ],
  },
  {
    id: 'p2',
    name: 'Noir Essence',
    brand: 'Maison Lumiere',
    year: 2020,
    concentration: 'EDP',
    family: 'ambar especiado',
    notes: { top: ['cardamomo', 'pimienta'], heart: ['rosa', 'incienso'], base: ['pachuli', 'ambar'] },
    tags: ['nocturno', 'invierno', 'noche', 'intenso', 'especiado', 'cita'],
    averageRating: 4.7,
    ratingCount: 310,
    averageLongevityHours: 10,
    averageIntensity: 'fuerte',
    usageStats: { day: 20, night: 80, summer: 10, winter: 90, office: 30, date: 80 },
    imageUrl: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=800&q=80',
    backgroundTheme: 'dark-leather',
    buyLinks: [
      { label: 'Ver en tienda A', url: 'https://example.com/tienda-a/noir-essence' },
      { label: 'Ver en tienda B', url: 'https://example.com/tienda-b/noir-essence' },
    ],
  },
  {
    id: 'p3',
    name: 'Ocean Mist',
    brand: 'Nordic Wave',
    year: 2021,
    concentration: 'EDT',
    family: 'acuatico',
    notes: { top: ['ozono', 'sal marina'], heart: ['lirio', 'jazmin'], base: ['cedro', 'almizcle'] },
    tags: ['acuatico', 'marino', 'dia', 'fresco', 'verano', 'casual'],
    averageRating: 4.1,
    ratingCount: 180,
    averageLongevityHours: 6,
    averageIntensity: 'suave',
    usageStats: { day: 80, night: 20, summer: 75, winter: 25, office: 70, date: 30 },
    imageUrl: 'https://images.unsplash.com/photo-1470058869958-2a77ade41c02?auto=format&fit=crop&w=800&q=80',
    backgroundTheme: 'aquatic-blue',
    buyLinks: [{ label: 'Ver en tienda A', url: 'https://example.com/tienda-a/ocean-mist' }],
  },
  {
    id: 'p4',
    name: 'Woodland Trail',
    brand: 'Terra Alba',
    year: 2019,
    concentration: 'EDP',
    family: 'amaderado',
    notes: { top: ['cedro'], heart: ['vetiver', 'cipres'], base: ['musgo', 'ambar'] },
    tags: ['amaderado', 'otono', 'invierno', 'noche', 'verde', 'bosque'],
    averageRating: 4.3,
    ratingCount: 190,
    averageLongevityHours: 8,
    averageIntensity: 'media',
    usageStats: { day: 40, night: 60, summer: 35, winter: 65, office: 55, date: 45 },
    imageUrl: 'https://images.unsplash.com/photo-1525286116112-b59af11adad1?auto=format&fit=crop&w=800&q=80',
    backgroundTheme: 'woody-brown',
    buyLinks: [{ label: 'Ver en tienda B', url: 'https://example.com/tienda-b/woodland-trail' }],
  },
  {
    id: 'p5',
    name: 'Velvet Sky',
    brand: 'Lune',
    year: 2018,
    concentration: 'Parfum',
    family: 'dulce oriental',
    notes: { top: ['mandarina'], heart: ['jazmin', 'heliotropo'], base: ['vainilla', 'tonka', 'almizcle'] },
    tags: ['dulce', 'noche', 'invierno', 'gourmand', 'cita'],
    averageRating: 4.6,
    ratingCount: 260,
    averageLongevityHours: 9,
    averageIntensity: 'fuerte',
    usageStats: { day: 25, night: 75, summer: 20, winter: 80, office: 30, date: 85 },
    imageUrl: 'https://images.unsplash.com/photo-1524592094714-0f0654e20314?auto=format&fit=crop&w=800&q=80&sat=-80',
    backgroundTheme: 'gourmand-warm',
    buyLinks: [{ label: 'Ver en tienda A', url: 'https://example.com/tienda-a/velvet-sky' }],
  },
  {
    id: 'p6',
    name: 'Azure Drift',
    brand: 'Blue Current',
    year: 2023,
    concentration: 'EDT',
    family: 'ozonico',
    notes: { top: ['ozono', 'albahaca'], heart: ['nenufar', 'violeta'], base: ['cedro blanco', 'almizcle'] },
    tags: ['ozonico', 'acuatico', 'dia', 'verano', 'oficina', 'limpio'],
    averageRating: 4.2,
    ratingCount: 140,
    averageLongevityHours: 6,
    averageIntensity: 'suave',
    usageStats: { day: 78, night: 22, summer: 80, winter: 20, office: 72, date: 28 },
    imageUrl: 'https://images.unsplash.com/photo-1506617420156-8e4536971650?auto=format&fit=crop&w=800&q=80',
    backgroundTheme: 'aquatic-blue',
    buyLinks: [{ label: 'Ver en tienda A', url: 'https://example.com/perfume/azure-drift' }],
  },
  {
    id: 'p7',
    name: 'Green Canopy',
    brand: 'Botanic Air',
    year: 2021,
    concentration: 'EDT',
    family: 'verde aromatico',
    notes: { top: ['menta', 'hojas verdes'], heart: ['galbanum', 'lavanda'], base: ['vetiver', 'musgo'] },
    tags: ['verde', 'herbal', 'fresco', 'dia', 'primavera', 'oficina'],
    averageRating: 4.0,
    ratingCount: 120,
    averageLongevityHours: 7,
    averageIntensity: 'media',
    usageStats: { day: 80, night: 20, summer: 60, winter: 40, office: 70, date: 35 },
    imageUrl: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?auto=format&fit=crop&w=800&q=80',
    backgroundTheme: 'tropical-green',
    buyLinks: [{ label: 'Ver en tienda B', url: 'https://example.com/perfume/green-canopy' }],
  },
  {
    id: 'p8',
    name: 'Rose Mirage',
    brand: 'Fleur Blanche',
    year: 2017,
    concentration: 'EDP',
    family: 'floral',
    notes: { top: ['mandarina', 'rosa'], heart: ['jazmin', 'peonia'], base: ['almizcle', 'santal'] },
    tags: ['floral', 'floral blanco', 'primavera', 'dia', 'romantico'],
    averageRating: 4.5,
    ratingCount: 280,
    averageLongevityHours: 8,
    averageIntensity: 'media',
    usageStats: { day: 70, night: 30, summer: 55, winter: 45, office: 50, date: 75 },
    imageUrl: 'https://images.unsplash.com/photo-1499638673689-79a0b5115d87?auto=format&fit=crop&w=800&q=80',
    backgroundTheme: 'floral-pink',
    buyLinks: [{ label: 'Ver en tienda A', url: 'https://example.com/perfume/rose-mirage' }],
  },
  {
    id: 'p9',
    name: 'Amber Dune',
    brand: 'Sahara Notes',
    year: 2022,
    concentration: 'Parfum',
    family: 'oriental ambarado',
    notes: { top: ['azafran', 'canela'], heart: ['rosa', 'incienso'], base: ['ambar', 'cuero'] },
    tags: ['oriental', 'ambarado', 'noche', 'invierno', 'cita', 'cuero'],
    averageRating: 4.8,
    ratingCount: 320,
    averageLongevityHours: 11,
    averageIntensity: 'bestia',
    usageStats: { day: 15, night: 85, summer: 10, winter: 90, office: 25, date: 85 },
    imageUrl: 'https://images.unsplash.com/photo-1524592094714-0f0654e20314?auto=format&fit=crop&w=800&q=80&sat=50',
    backgroundTheme: 'dark-leather',
    buyLinks: [{ label: 'Ver en tienda B', url: 'https://example.com/perfume/amber-dune' }],
  },
  {
    id: 'p10',
    name: 'Vanilla Ember',
    brand: 'Sweet Craft',
    year: 2020,
    concentration: 'EDP',
    family: 'gourmand',
    notes: { top: ['vainilla'], heart: ['haba tonka', 'cacao'], base: ['madera de cachemira', 'almizcle'] },
    tags: ['gourmand', 'dulce', 'invierno', 'noche', 'postre'],
    averageRating: 4.6,
    ratingCount: 230,
    averageLongevityHours: 9,
    averageIntensity: 'fuerte',
    usageStats: { day: 30, night: 70, summer: 20, winter: 80, office: 30, date: 75 },
    imageUrl: 'https://images.unsplash.com/photo-1524592094714-0f0654e20314?auto=format&fit=crop&w=800&q=80&sat=-30',
    backgroundTheme: 'gourmand-warm',
    buyLinks: [{ label: 'Ver en tienda A', url: 'https://example.com/perfume/vanilla-ember' }],
  },
  {
    id: 'p11',
    name: 'Cedar Atlas',
    brand: 'Nord Woods',
    year: 2019,
    concentration: 'EDT',
    family: 'amaderado aromatico',
    notes: { top: ['bergamota', 'cipres'], heart: ['cedro', 'salvia'], base: ['vetiver', 'ambar'] },
    tags: ['amaderado', 'verde', 'otoño', 'invierno', 'oficina'],
    averageRating: 4.2,
    ratingCount: 150,
    averageLongevityHours: 8,
    averageIntensity: 'media',
    usageStats: { day: 55, night: 45, summer: 40, winter: 60, office: 65, date: 45 },
    imageUrl: 'https://images.unsplash.com/photo-1501004318641-b39e6451bec6?auto=format&fit=crop&w=800&q=80',
    backgroundTheme: 'woody-brown',
    buyLinks: [{ label: 'Ver en tienda B', url: 'https://example.com/perfume/cedar-atlas' }],
  },
  {
    id: 'p12',
    name: 'Tropical Haze',
    brand: 'Isla Norte',
    year: 2021,
    concentration: 'EDP',
    family: 'tropical frutal',
    notes: { top: ['piña', 'mango'], heart: ['coco', 'frangipani'], base: ['almizcle', 'santal'] },
    tags: ['tropical', 'frutal', 'verano', 'dia', 'playa'],
    averageRating: 4.3,
    ratingCount: 210,
    averageLongevityHours: 7,
    averageIntensity: 'media',
    usageStats: { day: 85, night: 15, summer: 90, winter: 10, office: 30, date: 55 },
    imageUrl: 'https://images.unsplash.com/photo-1506617420156-8e4536971650?auto=format&fit=crop&w=800&q=80&sat=20',
    backgroundTheme: 'tropical-green',
    buyLinks: [{ label: 'Ver en tienda A', url: 'https://example.com/perfume/tropical-haze' }],
  },
  {
    id: 'p13',
    name: 'Cobalt Fresh',
    brand: 'Urban Sea',
    year: 2020,
    concentration: 'EDT',
    family: 'fresco acuatico',
    notes: { top: ['menta', 'limon'], heart: ['lavanda', 'violeta'], base: ['cedro', 'almizcle'] },
    tags: ['fresco', 'acuatico', 'ozonico', 'dia', 'oficina', 'verano'],
    averageRating: 4.0,
    ratingCount: 130,
    averageLongevityHours: 6,
    averageIntensity: 'suave',
    usageStats: { day: 82, night: 18, summer: 80, winter: 20, office: 75, date: 30 },
    imageUrl: 'https://images.unsplash.com/photo-1470337458703-46ad1756a187?auto=format&fit=crop&w=800&q=80',
    backgroundTheme: 'aquatic-blue',
    buyLinks: [{ label: 'Ver en tienda B', url: 'https://example.com/perfume/cobalt-fresh' }],
  },
  {
    id: 'p14',
    name: 'Spice Route',
    brand: 'Atlas Ember',
    year: 2018,
    concentration: 'Parfum',
    family: 'especiado oriental',
    notes: { top: ['pimienta negra', 'cardamomo'], heart: ['canela', 'clavo'], base: ['ambar', 'cuero'] },
    tags: ['especiado', 'oriental', 'noche', 'invierno', 'fiesta'],
    averageRating: 4.7,
    ratingCount: 260,
    averageLongevityHours: 11,
    averageIntensity: 'bestia',
    usageStats: { day: 20, night: 80, summer: 15, winter: 85, office: 25, date: 80 },
    imageUrl: 'https://images.unsplash.com/photo-1524592094714-0f0654e20314?auto=format&fit=crop&w=800&q=80&sat=-20',
    backgroundTheme: 'dark-leather',
    buyLinks: [{ label: 'Ver en tienda A', url: 'https://example.com/perfume/spice-route' }],
  },
  {
    id: 'p15',
    name: 'Silk Peony',
    brand: 'Jardin Blanc',
    year: 2022,
    concentration: 'EDP',
    family: 'floral almizclado',
    notes: { top: ['pera', 'peonia'], heart: ['rosa', 'jazmin'], base: ['almizcle', 'santal'] },
    tags: ['floral', 'almizclado', 'primavera', 'dia', 'romantico'],
    averageRating: 4.4,
    ratingCount: 190,
    averageLongevityHours: 8,
    averageIntensity: 'media',
    usageStats: { day: 70, night: 30, summer: 60, winter: 40, office: 50, date: 70 },
    imageUrl: 'https://images.unsplash.com/photo-1501004318641-b39e6451bec6?auto=format&fit=crop&w=800&q=80&sat=10',
    backgroundTheme: 'floral-pink',
    buyLinks: [{ label: 'Ver en tienda B', url: 'https://example.com/perfume/silk-peony' }],
  },
  {
    id: 'p16',
    name: 'Café Noir',
    brand: 'Roast Lab',
    year: 2019,
    concentration: 'EDP',
    family: 'gourmand ahumado',
    notes: { top: ['cafe'], heart: ['jazmin', 'tonka'], base: ['humo', 'cedro'] },
    tags: ['gourmand', 'cafe', 'ahumado', 'noche', 'otoño'],
    averageRating: 4.5,
    ratingCount: 175,
    averageLongevityHours: 9,
    averageIntensity: 'fuerte',
    usageStats: { day: 30, night: 70, summer: 25, winter: 75, office: 35, date: 75 },
    imageUrl: 'https://images.unsplash.com/photo-1524592094714-0f0654e20314?auto=format&fit=crop&w=800&q=80&sat=-50',
    backgroundTheme: 'gourmand-warm',
    buyLinks: [{ label: 'Ver en tienda A', url: 'https://example.com/perfume/cafe-noir' }],
  },
  {
    id: 'p17',
    name: 'Pure Cotton',
    brand: 'Clean Air',
    year: 2020,
    concentration: 'EDT',
    family: 'almizclado limpio',
    notes: { top: ['aldehidos'], heart: ['lirio del valle'], base: ['almizcle blanco', 'cedro'] },
    tags: ['limpio', 'algodon', 'dia', 'oficina', 'verano'],
    averageRating: 3.9,
    ratingCount: 110,
    averageLongevityHours: 5,
    averageIntensity: 'suave',
    usageStats: { day: 85, night: 15, summer: 70, winter: 30, office: 80, date: 25 },
    imageUrl: 'https://images.unsplash.com/photo-1470337458703-46ad1756a187?auto=format&fit=crop&w=800&q=80&sat=-40',
    backgroundTheme: 'clean-blue',
    buyLinks: [{ label: 'Ver en tienda B', url: 'https://example.com/perfume/pure-cotton' }],
  },
  {
    id: 'p18',
    name: 'Leather Smoke',
    brand: 'Noctis',
    year: 2021,
    concentration: 'Parfum',
    family: 'cuero ahumado',
    notes: { top: ['ahumado'], heart: ['cuero', 'incienso'], base: ['tabaco', 'ambar'] },
    tags: ['cuero', 'ahumado', 'tabaco', 'noche', 'invierno'],
    averageRating: 4.6,
    ratingCount: 210,
    averageLongevityHours: 12,
    averageIntensity: 'bestia',
    usageStats: { day: 10, night: 90, summer: 5, winter: 95, office: 20, date: 85 },
    imageUrl: 'https://images.unsplash.com/photo-1475180098004-ca77a66827be?auto=format&fit=crop&w=800&q=80',
    backgroundTheme: 'dark-leather',
    buyLinks: [{ label: 'Ver en tienda A', url: 'https://example.com/perfume/leather-smoke' }],
  },
  {
    id: 'p19',
    name: 'Coconut Shore',
    brand: 'Isla Norte',
    year: 2023,
    concentration: 'EDT',
    family: 'tropical coco',
    notes: { top: ['limon', 'coco'], heart: ['tiaré', 'frangipani'], base: ['almizcle', 'santal'] },
    tags: ['tropical', 'playa', 'verano', 'dia', 'coco'],
    averageRating: 4.2,
    ratingCount: 150,
    averageLongevityHours: 7,
    averageIntensity: 'media',
    usageStats: { day: 88, night: 12, summer: 90, winter: 10, office: 25, date: 55 },
    imageUrl: 'https://images.unsplash.com/photo-1506617420156-8e4536971650?auto=format&fit=crop&w=800&q=80&sat=40',
    backgroundTheme: 'tropical-green',
    buyLinks: [{ label: 'Ver en tienda B', url: 'https://example.com/perfume/coconut-shore' }],
  },
  {
    id: 'p20',
    name: 'Smoke & Velvet',
    brand: 'Obsidian',
    year: 2018,
    concentration: 'Parfum',
    family: 'ambar ahumado',
    notes: { top: ['incienso', 'pimienta'], heart: ['rosa', 'iris'], base: ['ambar', 'oud'] },
    tags: ['ahumado', 'oud', 'noche', 'invierno', 'formal'],
    averageRating: 4.7,
    ratingCount: 240,
    averageLongevityHours: 12,
    averageIntensity: 'bestia',
    usageStats: { day: 15, night: 85, summer: 10, winter: 90, office: 25, date: 85 },
    imageUrl: 'https://images.unsplash.com/photo-1524592094714-0f0654e20314?auto=format&fit=crop&w=800&q=80&sat=-70',
    backgroundTheme: 'dark-leather',
    buyLinks: [{ label: 'Ver en tienda A', url: 'https://example.com/perfume/smoke-velvet' }],
  },
  {
    id: 'p21',
    name: 'Citrus Vetiver',
    brand: 'Atelier Verde',
    year: 2021,
    concentration: 'EDT',
    family: 'citrico amaderado',
    notes: { top: ['pomelo', 'limon'], heart: ['vetiver', 'salvia'], base: ['cedro', 'almizcle'] },
    tags: ['citrico', 'verde', 'dia', 'verano', 'oficina'],
    averageRating: 4.1,
    ratingCount: 160,
    averageLongevityHours: 7,
    averageIntensity: 'media',
    usageStats: { day: 78, night: 22, summer: 75, winter: 25, office: 68, date: 35 },
    imageUrl: 'https://images.unsplash.com/photo-1501004318641-b39e6451bec6?auto=format&fit=crop&w=800&q=80&sat=30',
    backgroundTheme: 'citrus-yellow',
    buyLinks: [{ label: 'Ver en tienda B', url: 'https://example.com/perfume/citrus-vetiver' }],
  },
  {
    id: 'p22',
    name: 'Iris Cloud',
    brand: 'Fleur Blanche',
    year: 2019,
    concentration: 'EDP',
    family: 'iris empolvado',
    notes: { top: ['violeta'], heart: ['iris', 'heliotropo'], base: ['almizcle', 'vainilla'] },
    tags: ['iris', 'empolvado', 'floral', 'oficina', 'primavera'],
    averageRating: 4.3,
    ratingCount: 140,
    averageLongevityHours: 8,
    averageIntensity: 'media',
    usageStats: { day: 70, night: 30, summer: 55, winter: 45, office: 65, date: 55 },
    imageUrl: 'https://images.unsplash.com/photo-1499638673689-79a0b5115d87?auto=format&fit=crop&w=800&q=80&sat=30',
    backgroundTheme: 'floral-pink',
    buyLinks: [{ label: 'Ver en tienda A', url: 'https://example.com/perfume/iris-cloud' }],
  },
  {
    id: 'p23',
    name: 'Incense Trail',
    brand: 'Noctis',
    year: 2020,
    concentration: 'EDP',
    family: 'incienso amaderado',
    notes: { top: ['incienso'], heart: ['mirra', 'cedro'], base: ['ambar', 'madera de gaiac'] },
    tags: ['incienso', 'amaderado', 'otoño', 'noche', 'formal'],
    averageRating: 4.4,
    ratingCount: 170,
    averageLongevityHours: 9,
    averageIntensity: 'fuerte',
    usageStats: { day: 35, night: 65, summer: 20, winter: 80, office: 40, date: 70 },
    imageUrl: 'https://images.unsplash.com/photo-1475180098004-ca77a66827be?auto=format&fit=crop&w=800&q=80&sat=-10',
    backgroundTheme: 'dark-leather',
    buyLinks: [{ label: 'Ver en tienda B', url: 'https://example.com/perfume/incense-trail' }],
  },
  {
    id: 'p24',
    name: 'Lavender Shore',
    brand: 'Botanic Air',
    year: 2021,
    concentration: 'EDT',
    family: 'aromatico fougere',
    notes: { top: ['lavanda', 'romero'], heart: ['geranio', 'musgo'], base: ['tonka', 'cedro'] },
    tags: ['fougere', 'lavanda', 'clasico', 'oficina', 'barbershop'],
    averageRating: 4.0,
    ratingCount: 125,
    averageLongevityHours: 7,
    averageIntensity: 'media',
    usageStats: { day: 75, night: 25, summer: 55, winter: 45, office: 78, date: 35 },
    imageUrl: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?auto=format&fit=crop&w=800&q=80&sat=-20',
    backgroundTheme: 'clean-blue',
    buyLinks: [{ label: 'Ver en tienda A', url: 'https://example.com/perfume/lavender-shore' }],
  },
  {
    id: 'p25',
    name: 'Cocoa Ember',
    brand: 'Sweet Craft',
    year: 2022,
    concentration: 'Parfum',
    family: 'gourmand cacao',
    notes: { top: ['cacao'], heart: ['vainilla', 'caramelo'], base: ['santal', 'ambar'] },
    tags: ['gourmand', 'dulce', 'invierno', 'noche', 'postre'],
    averageRating: 4.5,
    ratingCount: 190,
    averageLongevityHours: 10,
    averageIntensity: 'fuerte',
    usageStats: { day: 25, night: 75, summer: 20, winter: 80, office: 20, date: 80 },
    imageUrl: 'https://images.unsplash.com/photo-1501004318641-b39e6451bec6?auto=format&fit=crop&w=800&q=80&sat=-10',
    backgroundTheme: 'gourmand-warm',
    buyLinks: [{ label: 'Ver en tienda B', url: 'https://example.com/perfume/cocoa-ember' }],
  },
  {
    id: 'p26',
    name: 'Mango Sun',
    brand: 'Isla Norte',
    year: 2023,
    concentration: 'EDT',
    family: 'frutal tropical',
    notes: { top: ['mango', 'papaya'], heart: ['azahar', 'coco'], base: ['almizcle', 'santal'] },
    tags: ['tropical', 'frutal', 'verano', 'dia', 'playa'],
    averageRating: 4.2,
    ratingCount: 160,
    averageLongevityHours: 7,
    averageIntensity: 'media',
    usageStats: { day: 88, night: 12, summer: 90, winter: 10, office: 25, date: 55 },
    imageUrl: 'https://images.unsplash.com/photo-1475180098004-ca77a66827be?auto=format&fit=crop&w=800&q=80&sat=30',
    backgroundTheme: 'tropical-green',
    buyLinks: [{ label: 'Ver en tienda A', url: 'https://example.com/perfume/mango-sun' }],
  },
  {
    id: 'p27',
    name: 'Iced Neroli',
    brand: 'Atelier Verde',
    year: 2020,
    concentration: 'EDT',
    family: 'citrico aromatico',
    notes: { top: ['neroli', 'limon'], heart: ['albahaca', 'vetiver'], base: ['almizcle', 'cedro'] },
    tags: ['citrico', 'neroli', 'fresco', 'dia', 'verano', 'oficina'],
    averageRating: 4.1,
    ratingCount: 150,
    averageLongevityHours: 6,
    averageIntensity: 'suave',
    usageStats: { day: 82, night: 18, summer: 80, winter: 20, office: 72, date: 32 },
    imageUrl: 'https://images.unsplash.com/photo-1470337458703-46ad1756a187?auto=format&fit=crop&w=800&q=80&sat=-10',
    backgroundTheme: 'citrus-yellow',
    buyLinks: [{ label: 'Ver en tienda B', url: 'https://example.com/perfume/iced-neroli' }],
  },
  {
    id: 'p28',
    name: 'Black Vanilla',
    brand: 'Obsidian',
    year: 2017,
    concentration: 'Parfum',
    family: 'ambar vainilla',
    notes: { top: ['ciruela'], heart: ['vainilla negra', 'orquidea'], base: ['ambar', 'benjui'] },
    tags: ['vainilla', 'ambarado', 'dulce', 'noche', 'invierno'],
    averageRating: 4.6,
    ratingCount: 260,
    averageLongevityHours: 11,
    averageIntensity: 'bestia',
    usageStats: { day: 20, night: 80, summer: 15, winter: 85, office: 25, date: 85 },
    imageUrl: 'https://images.unsplash.com/photo-1524592094714-0f0654e20314?auto=format&fit=crop&w=800&q=80&sat=-60',
    backgroundTheme: 'gourmand-warm',
    buyLinks: [{ label: 'Ver en tienda A', url: 'https://example.com/perfume/black-vanilla' }],
  },
  {
    id: 'p29',
    name: 'Cedar Citrus',
    brand: 'Nord Woods',
    year: 2022,
    concentration: 'EDT',
    family: 'amaderado citrico',
    notes: { top: ['pomelo'], heart: ['cedro', 'tomillo'], base: ['vetiver', 'musgo'] },
    tags: ['amaderado', 'citrico', 'dia', 'primavera', 'oficina'],
    averageRating: 4.0,
    ratingCount: 130,
    averageLongevityHours: 7,
    averageIntensity: 'media',
    usageStats: { day: 78, night: 22, summer: 70, winter: 30, office: 70, date: 40 },
    imageUrl: 'https://images.unsplash.com/photo-1501004318641-b39e6451bec6?auto=format&fit=crop&w=800&q=80&sat=5',
    backgroundTheme: 'woody-brown',
    buyLinks: [{ label: 'Ver en tienda B', url: 'https://example.com/perfume/cedar-citrus' }],
  },
  {
    id: 'p30',
    name: 'Amber Suede',
    brand: 'Maison Lumiere',
    year: 2021,
    concentration: 'EDP',
    family: 'ambar cuero',
    notes: { top: ['azafran'], heart: ['suede', 'rosa'], base: ['ambar', 'gamuza'] },
    tags: ['cuero', 'ambarado', 'otoño', 'noche', 'formal'],
    averageRating: 4.5,
    ratingCount: 200,
    averageLongevityHours: 10,
    averageIntensity: 'fuerte',
    usageStats: { day: 30, night: 70, summer: 20, winter: 80, office: 35, date: 80 },
    imageUrl: 'https://images.unsplash.com/photo-1475180098004-ca77a66827be?auto=format&fit=crop&w=800&q=80&sat=-30',
    backgroundTheme: 'dark-leather',
    buyLinks: [{ label: 'Ver en tienda A', url: 'https://example.com/perfume/amber-suede' }],
  },
  {
    id: 'p31',
    name: 'Jasmine Veil',
    brand: 'Fleur Blanche',
    year: 2020,
    concentration: 'EDP',
    family: 'floral blanco',
    notes: { top: ['neroli'], heart: ['jazmin sambac', 'ylang-ylang'], base: ['almizcle', 'madera blanca'] },
    tags: ['floral blanco', 'romantico', 'primavera', 'verano', 'dia'],
    averageRating: 4.4,
    ratingCount: 210,
    averageLongevityHours: 8,
    averageIntensity: 'media',
    usageStats: { day: 68, night: 32, summer: 60, winter: 40, office: 55, date: 75 },
    imageUrl: 'https://images.unsplash.com/photo-1499638673689-79a0b5115d87?auto=format&fit=crop&w=800&q=80&sat=15',
    backgroundTheme: 'floral-pink',
    buyLinks: [{ label: 'Ver en tienda B', url: 'https://example.com/perfume/jasmine-veil' }],
  },
  {
    id: 'p32',
    name: 'Salty Breeze',
    brand: 'Urban Sea',
    year: 2022,
    concentration: 'EDT',
    family: 'marino salado',
    notes: { top: ['sal marina', 'bergamota'], heart: ['lirio de mar'], base: ['almizcle', 'driftwood'] },
    tags: ['marino', 'salado', 'acuatico', 'verano', 'dia', 'playa'],
    averageRating: 4.1,
    ratingCount: 145,
    averageLongevityHours: 6,
    averageIntensity: 'suave',
    usageStats: { day: 82, night: 18, summer: 85, winter: 15, office: 60, date: 40 },
    imageUrl: 'https://images.unsplash.com/photo-1470058869958-2a77ade41c02?auto=format&fit=crop&w=800&q=80&sat=30',
    backgroundTheme: 'aquatic-blue',
    buyLinks: [{ label: 'Ver en tienda A', url: 'https://example.com/perfume/salty-breeze' }],
  },
  {
    id: 'p33',
    name: 'Amber Cocoa',
    brand: 'Sweet Craft',
    year: 2021,
    concentration: 'Parfum',
    family: 'gourmand ambarado',
    notes: { top: ['cacao'], heart: ['caramelo', 'canela'], base: ['ambar', 'tonka'] },
    tags: ['gourmand', 'ambarado', 'dulce', 'noche', 'invierno'],
    averageRating: 4.5,
    ratingCount: 185,
    averageLongevityHours: 10,
    averageIntensity: 'fuerte',
    usageStats: { day: 28, night: 72, summer: 20, winter: 80, office: 22, date: 78 },
    imageUrl: 'https://images.unsplash.com/photo-1524592094714-0f0654e20314?auto=format&fit=crop&w=800&q=80&sat=-55',
    backgroundTheme: 'gourmand-warm',
    buyLinks: [{ label: 'Ver en tienda B', url: 'https://example.com/perfume/amber-cocoa' }],
  },
  {
    id: 'p34',
    name: 'Vetiver Smoke',
    brand: 'Nord Woods',
    year: 2018,
    concentration: 'EDP',
    family: 'amaderado ahumado',
    notes: { top: ['pimienta'], heart: ['vetiver ahumado'], base: ['cedro', 'ambar'] },
    tags: ['ahumado', 'vetiver', 'otoño', 'noche', 'formal'],
    averageRating: 4.3,
    ratingCount: 170,
    averageLongevityHours: 9,
    averageIntensity: 'fuerte',
    usageStats: { day: 35, night: 65, summer: 25, winter: 75, office: 38, date: 72 },
    imageUrl: 'https://images.unsplash.com/photo-1475180098004-ca77a66827be?auto=format&fit=crop&w=800&q=80&sat=-20',
    backgroundTheme: 'dark-leather',
    buyLinks: [{ label: 'Ver en tienda A', url: 'https://example.com/perfume/vetiver-smoke' }],
  },
  {
    id: 'p35',
    name: 'Silver Musk',
    brand: 'Clean Air',
    year: 2022,
    concentration: 'EDT',
    family: 'almizclado limpio',
    notes: { top: ['aldehidos'], heart: ['iris'], base: ['almizcle blanco', 'cedro'] },
    tags: ['limpio', 'algodon', 'oficina', 'dia', 'verano'],
    averageRating: 3.9,
    ratingCount: 120,
    averageLongevityHours: 6,
    averageIntensity: 'suave',
    usageStats: { day: 82, night: 18, summer: 70, winter: 30, office: 85, date: 30 },
    imageUrl: 'https://images.unsplash.com/photo-1470337458703-46ad1756a187?auto=format&fit=crop&w=800&q=80&sat=-20',
    backgroundTheme: 'clean-blue',
    buyLinks: [{ label: 'Ver en tienda B', url: 'https://example.com/perfume/silver-musk' }],
  },
  {
    id: 'p36',
    name: 'Citrus Spice',
    brand: 'Atlas Ember',
    year: 2023,
    concentration: 'EDP',
    family: 'citrico especiado',
    notes: { top: ['naranja sanguina'], heart: ['cardamomo', 'lavanda'], base: ['cedro', 'ambar'] },
    tags: ['citrico', 'especiado', 'dia', 'otono', 'oficina'],
    averageRating: 4.2,
    ratingCount: 155,
    averageLongevityHours: 8,
    averageIntensity: 'media',
    usageStats: { day: 78, night: 22, summer: 60, winter: 40, office: 65, date: 45 },
    imageUrl: 'https://images.unsplash.com/photo-1501004318641-b39e6451bec6?auto=format&fit=crop&w=800&q=80&sat=25',
    backgroundTheme: 'citrus-yellow',
    buyLinks: [{ label: 'Ver en tienda A', url: 'https://example.com/perfume/citrus-spice' }],
  },
  {
    id: 'p37',
    name: 'Mint Breeze',
    brand: 'Urban Sea',
    year: 2021,
    concentration: 'EDT',
    family: 'menta acuatico',
    notes: { top: ['menta', 'limon'], heart: ['lavanda', 'violeta'], base: ['cedro', 'almizcle'] },
    tags: ['menta', 'acuatico', 'fresco', 'dia', 'verano', 'oficina'],
    averageRating: 4.0,
    ratingCount: 145,
    averageLongevityHours: 6,
    averageIntensity: 'suave',
    usageStats: { day: 80, night: 20, summer: 78, winter: 22, office: 72, date: 35 },
    imageUrl: 'https://images.unsplash.com/photo-1470058869958-2a77ade41c02?auto=format&fit=crop&w=800&q=80&sat=10',
    backgroundTheme: 'aquatic-blue',
    buyLinks: [{ label: 'Ver en tienda B', url: 'https://example.com/perfume/mint-breeze' }],
  },
  {
    id: 'p38',
    name: 'Oud Royale',
    brand: 'Noctis',
    year: 2019,
    concentration: 'Parfum',
    family: 'oud ambarado',
    notes: { top: ['azafran'], heart: ['oud', 'rosa'], base: ['ambar', 'vainilla'] },
    tags: ['oud', 'ambarado', 'noche', 'invierno', 'formal'],
    averageRating: 4.8,
    ratingCount: 290,
    averageLongevityHours: 12,
    averageIntensity: 'bestia',
    usageStats: { day: 10, night: 90, summer: 10, winter: 90, office: 20, date: 90 },
    imageUrl: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=800&q=80&sat=-10',
    backgroundTheme: 'dark-leather',
    buyLinks: [{ label: 'Ver en tienda A', url: 'https://example.com/perfume/oud-royale' }],
  },
  {
    id: 'p39',
    name: 'Ginger Spark',
    brand: 'Atlas Ember',
    year: 2022,
    concentration: 'EDP',
    family: 'especiado fresco',
    notes: { top: ['jengibre', 'limon'], heart: ['cardamomo', 'salvia'], base: ['vetiver', 'almizcle'] },
    tags: ['jengibre', 'fresco', 'dia', 'verano', 'casual'],
    averageRating: 4.1,
    ratingCount: 135,
    averageLongevityHours: 7,
    averageIntensity: 'media',
    usageStats: { day: 80, night: 20, summer: 78, winter: 22, office: 60, date: 45 },
    imageUrl: 'https://images.unsplash.com/photo-1470337458703-46ad1756a187?auto=format&fit=crop&w=800&q=80&sat=20',
    backgroundTheme: 'citrus-yellow',
    buyLinks: [{ label: 'Ver en tienda B', url: 'https://example.com/perfume/ginger-spark' }],
  },
  {
    id: 'p40',
    name: 'Berry Bloom',
    brand: 'Fleur Blanche',
    year: 2023,
    concentration: 'EDP',
    family: 'frutal floral',
    notes: { top: ['frambuesa', 'grosella'], heart: ['peonia', 'rosa'], base: ['almizcle', 'santal'] },
    tags: ['frutal', 'floral', 'primavera', 'dia', 'romantico'],
    averageRating: 4.2,
    ratingCount: 150,
    averageLongevityHours: 7,
    averageIntensity: 'media',
    usageStats: { day: 76, night: 24, summer: 70, winter: 30, office: 50, date: 72 },
    imageUrl: 'https://images.unsplash.com/photo-1499638673689-79a0b5115d87?auto=format&fit=crop&w=800&q=80&sat=35',
    backgroundTheme: 'floral-pink',
    buyLinks: [{ label: 'Ver en tienda A', url: 'https://example.com/perfume/berry-bloom' }],
  },
];

const preferencesByUser: Record<string, UserPreferences> = {
  'user-1': {
    userId: 'user-1',
    likes: ['p1', 'p3', 'p4', 'p8', 'p12', 'p20'],
    dislikes: ['p18'],
    favorites: ['p1', 'p4', 'p9'],
    wantToTry: ['p5', 'p38'],
    haveIt: ['p3'],
  },
};

const reviews: UserReview[] = [
  { userId: 'user-1', perfumeId: 'p1', rating: 4, comment: 'Fresco y facil de usar', createdAt: new Date() },
  { userId: 'user-2', perfumeId: 'p2', rating: 5, comment: 'Intenso y elegante', createdAt: new Date() },
  { userId: 'user-3', perfumeId: 'p9', rating: 5, comment: 'Ambarado profundo para noches frias', createdAt: new Date() },
  { userId: 'user-4', perfumeId: 'p12', rating: 4, comment: 'Tropical divertido, ideal verano', createdAt: new Date() },
];

function ensureUserPreferences(userId: string): UserPreferences {
  if (!preferencesByUser[userId]) {
    preferencesByUser[userId] = { userId, likes: [], dislikes: [], favorites: [], wantToTry: [], haveIt: [] };
  }
  return preferencesByUser[userId];
}

function toggleInList(list: string[], perfumeId: string) {
  const exists = list.includes(perfumeId);
  if (exists) {
    return list.filter((id) => id !== perfumeId);
  }
  return [...list, perfumeId];
}

const actionMap: Record<PreferenceAction, keyof UserPreferences> = {
  like: 'likes',
  dislike: 'dislikes',
  favorite: 'favorites',
  wantToTry: 'wantToTry',
  haveIt: 'haveIt',
};

function applyPreferenceAction(userId: string, perfumeId: string, action: PreferenceAction): UserPreferences {
  const prefs = ensureUserPreferences(userId);
  const targetKey = actionMap[action];
  if (action === 'like') {
    prefs.dislikes = prefs.dislikes.filter((id) => id !== perfumeId);
  }
  if (action === 'dislike') {
    prefs.likes = prefs.likes.filter((id) => id !== perfumeId);
  }
  prefs[targetKey] = toggleInList(prefs[targetKey], perfumeId);
  return prefs;
}

export const perfumeService = {
  listPerfumes: (filters?: { name?: string; brand?: string; tag?: string }) => {
    const nameTerm = filters?.name?.toLowerCase() || '';
    const brandTerm = filters?.brand?.toLowerCase() || '';
    const tagTerm = filters?.tag?.toLowerCase() || '';

    return perfumes.filter((perfume) => {
      const matchesName = !nameTerm || perfume.name.toLowerCase().includes(nameTerm);
      const matchesBrand = !brandTerm || perfume.brand.toLowerCase().includes(brandTerm);
      const matchesTag = !tagTerm || perfume.tags.some((tag) => tag.toLowerCase() === tagTerm);
      return matchesName && matchesBrand && matchesTag;
    });
  },

  getPerfumeById: (id: string) => perfumes.find((perfume) => perfume.id === id),
  getAll: () => perfumes,

  getUserPreferences: (userId: string) => ensureUserPreferences(userId),

  updateUserPreference: (userId: string, perfumeId: string, action: PreferenceAction) => {
    return applyPreferenceAction(userId, perfumeId, action);
  },

  getReviewsByPerfume: (perfumeId: string) => reviews.filter((review) => review.perfumeId === perfumeId),

  addReview: (review: Omit<UserReview, 'createdAt'>) => {
    const newReview: UserReview = { ...review, createdAt: new Date() };
    reviews.push(newReview);
    return newReview;
  },
};
